blank_issues_enabled: false
contact_links:
  - name: Tough as Client Discord
    url: https://discord.gg/2qYEHT3BWK
    about: For assistance, discussion, and help
  - name: Tough as Client Wiki
    url: https://github.com/fishcute/ToughAsClient/wiki
    about: The wiki for Tough as Client
